[package]
name = "day2"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input_reader = { path = "../input_reader" }
